name: Submit Gradle Dependency Graph

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate and Submit Dependency Graph
        uses: gradle/actions/dependency-submission@v3
        with:
          # Tells the action to install and run Gradle directly 
          # instead of looking for a root ./gradlew file
          gradle-version: 'current'
