name: Submit Gradle Dependency Graph

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # List all relative paths containing a build.gradle file
        project-dir:
          - '././/output-management/web-viewer/favorites/favorites'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Submit Dependency Graph for ${{ matrix.project-dir }}
        uses: gradle/actions/dependency-submission@v3
        with:
          gradle-version: 'current'
          build-root-directory: ${{ matrix.project-dir }}
